#![allow(dead_code)]
pub const WRONG_NUMBER_OF_BLINDINGS: u8 = 40u8;
pub const INVALID_BIT_SIZE: u8 = 41u8;
pub const INVALID_AGGREGATION: u8 = 42u8;
pub const INVALID_GENERATORS_LENGTH: u8 = 43u8;
pub const WRONG_NUMBER_OF_BIT_COMMITMENTS: u8 = 44u8;
pub const WRONG_NUMBER_OF_POLY_COMMITMENTS: u8 = 45u8;
pub const WRONG_NUMBER_OF_PROOF_SHARES: u8 = 46u8;
pub const MALFORMED_PROOF_SHARES: u8 = 47u8;
pub const MALICIOUS_DEALER: u8 = 51u8;
pub const VERIFICATION_ERROR: u8 = 52u8;
